In [1]:
from pymongo import MongoClient
import pandas as pd
from google.oauth2 import service_account
client=MongoClient("mongodb://localhost:27017/")
db=client["earthquick_db"]
collection=db["raw_earthquick_data"]
raw_events=list(collection.find())
print(f"Found raw records{len(raw_events)}")
if len(raw_events)==0:
    pass
else:
    for event in raw_events:
        if '_id' in event:
            del event['_id']
    df=pd.json_normalize(raw_events)
    df.columns=df.columns.str.replace('.', '_', regex=False)
    #Bigquery connection
    key_path=r"C:\Users\QC#\Downloads\dbt-learning-493706-81ad6e669580.json"
    credentials=service_account.Credentials.from_service_account_file(key_path)
    project_id="dbt-learning-493706"
    dataset_id="Earthquake_raw"
    table_id="raw_usgs_data"
    full_path=f"{project_id}.{dataset_id}.{table_id}"
    df.to_gbq(
       destination_table=full_path,
       credentials=credentials,
       if_exists="replace",
       progress_bar=True
    )

Found raw records20165

C:\Users\QC#\AppData\Local\Temp\ipykernel_5968\2976885750.py:24: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  df.to_gbq(
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 4215.38it/s]

In [2]:
df

,type,id,properties_mag,properties_place,properties_time,properties_updated,properties_tz,properties_url,properties_detail,properties_felt,...,properties_types,properties_nst,properties_dmin,properties_rms,properties_gap,properties_magType,properties_type,properties_title,geometry_type,geometry_coordinates
0,Feature,nc75386256,0.21000,"10 km NW of The Geysers, CA",1782721630680,1782721729579,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,",8.0,0.001626,0.01,126.0,md,earthquake,"M 0.2 - 10 km NW of The Geysers, CA",Point,"[-122.837501525879, 38.8390007019043, 1.909999..."
1,Feature,nc75386251,0.91000,"10 km ESE of Cloverdale, CA",1782721115550,1782721214716,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,",10.0,0.053690,0.02,230.0,md,earthquake,"M 0.9 - 10 km ESE of Cloverdale, CA",Point,"[-122.917663574219, 38.7691650390625, 6.010000..."
2,Feature,hv74993327,1.76000,"2 km N of Volcano, Hawaii",1782720921620,1782721131130,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",origin,phase-data,",37.0,0.038740,0.13,53.0,md,earthquake,"M 1.8 - 2 km N of Volcano, Hawaii",Point,"[-155.234329223633, 19.4621658325195, 27.38999..."
3,Feature,nc75386246,0.75000,"6 km NW of The Geysers, CA",1782720005920,1782720103355,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,",13.0,0.009529,0.02,67.0,md,earthquake,"M 0.8 - 6 km NW of The Geysers, CA",Point,"[-122.801170349121, 38.816333770752, 2.4800000..."
4,Feature,nc75386241,0.70000,"7 km WNW of Cobb, CA",1782719731210,1782719828376,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",nearby-cities,origin,phase-data,",13.0,0.012840,0.01,60.0,md,earthquake,"M 0.7 - 7 km WNW of Cobb, CA",Point,"[-122.806831359863, 38.8359985351562, 2.230000..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20021,Feature,us6000syjj,4.40000,"183 km ESE of Tadine, New Caledonia",1778330588505,1779273151040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",17.0,2.099000,0.86,128.0,mb,earthquake,"M 4.4 - 183 km ESE of Tadine, New Caledonia",Point,"[169.6006, -21.9573, 10]"
20022,Feature,us7000srv9,2.60000,"287 km WSW of Adak, Alaska",1778330564930,1782288753040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",13.0,0.231000,0.64,256.0,ml,earthquake,"M 2.6 - 287 km WSW of Adak, Alaska",Point,"[179.3869, 51.1536, 23.428]"
20023,Feature,aka2026jdkbpw,2.30000,"53 km W of Adak, Alaska",1778330256723,1781031529281,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",16.0,0.100000,0.80,146.0,ml,earthquake,"M 2.3 - 53 km W of Adak, Alaska",Point,"[-177.396, 51.808, 26.2]"
20024,Feature,aka2026jdjxxq,1.70000,"27 km SSE of Pope-Vannoy Landing, Alaska",1778329998924,1781031445548,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",30.0,0.400000,0.60,59.0,ml,earthquake,"M 1.7 - 27 km SSE of Pope-Vannoy Landing, Alaska",Point,"[-154.272, 59.343, 7.8]"
20025,Feature,ci41459440,1.54972,"14 km S of Anza, CA",1778329908840,1778337478813,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",nearby-cities,origin,phase-data,scitech-link,",25.0,0.139500,0.15,57.0,ml,earthquake,"M 1.5 - 14 km S of Anza, CA",Point,"[-116.648833333333, 33.4276666666667, 8.4]"

In [3]:
df1=df.astype(str)

In [4]:
df1.duplicated().sum()

np.int64(0)

In [5]:
df.columns

Index(['type', 'id', 'properties_mag', 'properties_place', 'properties_time',
       'properties_updated', 'properties_tz', 'properties_url',
       'properties_detail', 'properties_felt', 'properties_cdi',
       'properties_mmi', 'properties_alert', 'properties_status',
       'properties_tsunami', 'properties_sig', 'properties_net',
       'properties_code', 'properties_ids', 'properties_sources',
       'properties_types', 'properties_nst', 'properties_dmin',
       'properties_rms', 'properties_gap', 'properties_magType',
       'properties_type', 'properties_title', 'geometry_type',
       'geometry_coordinates'],
      dtype='object')

In [6]:
df.isna().sum()

type                        0
id                          0
properties_mag              5
properties_place            0
properties_time             0
properties_updated          0
properties_tz           20026
properties_url              0
properties_detail           0
properties_felt         19136
properties_cdi          19136
properties_mmi          19653
properties_alert        19891
properties_status           0
properties_tsunami          0
properties_sig              0
properties_net              0
properties_code             0
properties_ids              0
properties_sources          0
properties_types            0
properties_nst              2
properties_dmin             6
properties_rms              2
properties_gap              5
properties_magType          5
properties_type             0
properties_title            0
geometry_type               0
geometry_coordinates        0
dtype: int64

In [7]:
df.dtypes

type                     object
id                       object
properties_mag          float64
properties_place         object
properties_time           int64
properties_updated        int64
properties_tz            object
properties_url           object
properties_detail        object
properties_felt         float64
properties_cdi          float64
properties_mmi          float64
properties_alert         object
properties_status        object
properties_tsunami        int64
properties_sig            int64
properties_net           object
properties_code          object
properties_ids           object
properties_sources       object
properties_types         object
properties_nst          float64
properties_dmin         float64
properties_rms          float64
properties_gap          float64
properties_magType       object
properties_type          object
properties_title         object
geometry_type            object
geometry_coordinates     object
dtype: object

In [8]:
df[df['properties_tsunami']==1]

Empty DataFrame
Columns: [type, id, properties_mag, properties_place, properties_time, properties_updated, properties_tz, properties_url, properties_detail, properties_felt, properties_cdi, properties_mmi, properties_alert, properties_status, properties_tsunami, properties_sig, properties_net, properties_code, properties_ids, properties_sources, properties_types, properties_nst, properties_dmin, properties_rms, properties_gap, properties_magType, properties_type, properties_title, geometry_type, geometry_coordinates]
Index: []

[0 rows x 30 columns]

In [9]:
df['properties_tsunami'].value_counts()

properties_tsunami
0    20026
Name: count, dtype: int64